[package]
name = "day07"
version = "0.1.0"
authors = ["Robert Beier <r.beier199@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trees = "0.3.0"
regex = "1"
lazy_static = "1.4.0"
lib = {path = "../lib"}
